stages:

  ingest:
    cmd: python src/data_ingestion.py

    deps:
      - src/data_ingestion.py

    outs:
      - data/weather_data.csv:
          cache: true
          persist: true

    desc: "Fetch hourly weather data from Open-Meteo and append to weather_data.csv"